quiet: False
disable-version-string: True
with-expecter: True
filename: "{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
packages:
  github.com/andrii-lavreniuk/oapi-fiber-example/internal/interfaces:
    config:
      dir: "gen/mocks/interfaces"
    interfaces:
      Auth:
      AuthRepo:
      UsersRepo: